### ISSUE TITLE
How to fix openssl/rand.h' file not found

### ISSUE THREAD

**Issue by TeacherXue** [gejw0623/shadowsocks-iOS#1]
Hi ,when i running shadowsocks on iphone5s 8.3  , xcode 7.3,

openssl/rand.h' file not found

**Comment by Robin-JW** [comment]
you need git clone submodule, you can run:

```
git submodule init
git submodule update
```

**Comment by TeacherXue** [comment]
im running in shadowsocks-iOS-master
`git submodule init` 
`git submodule update`
but it doesn't work...What have I done wrong？

**Comment by Robin-JW** [comment]
like this?

```
cd shadowsocks-iOS
git submodule init
git submodule update
```

if not, please try to clone again

**Comment by TeacherXue** [comment]
thank u, i solve that. But It only runs on 32-bit phone?when i use iphone5s , xcode show 
`Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_ZXCapture", referenced from:
      objc-class-ref in QRCodeViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by Robin-JW** [comment]
i can run it on the iphone 5s 
you can try to check the QRCodeViewController file
